; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter, extra scripting
;   Upload options: custom port, speed and extra flags
;   Library options: dependencies, extra library storages
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[env]
platform = espressif32
framework = espidf
monitor_speed = 115200
build_flags = 
  	-D CONFIG_LOG_COLORS=1
	; Maximum log level for whole application (can be overruled for src files with LOG_LOCAL_LEVEL in build_src_flags)
	-D CORE_DEBUG_LEVEL=ESP_LOG_INFO

; Extend the default build flags (also for used libs) with additional flags for the src directory only
build_src_flags =
	-Og
	-Wall -Wextra
	-Wno-unused-parameter
    ; Maximum log level for src files, can be higher (or lower, equal) than CORE_DEBUG_LEVEL
	-D LOG_LOCAL_LEVEL=ESP_LOG_DEBUG

[env:esp32]
board=wemos_d1_mini32

[env:esp32s2]
board=lolin_s2_mini

[env:esp32s3]
board=lilygo-t3-s3

[env:esp32c3]
board=adafruit_qtpy_esp32c3

[env:esp32c6]
board=seeed_xiao_esp32c6
