; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter, extra scripting
;   Upload options: custom port, speed and extra flags
;   Library options: dependencies, extra library storages
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[env]
framework = arduino
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.311/platform-espressif32.zip

build_flags = 
	; Next line enables ESP-IDF logging, instead of (more bloated) Arduino based logging
	-D USE_ESP_IDF_LOG=1
  	-D CONFIG_LOG_COLORS=1
	; Maximum log level for whole application, incl libaries (can be overruled for src files with LOG_LOCAL_LEVEL in build_src_flags)
	; By using the numerical value 5 (i/o ESP_LOG_DEBUG) for CORE_DEBUG_LEVEL, you get very detailed Arduino boot logging
	;-D CORE_DEBUG_LEVEL=ESP_LOG_DEBUG
	-D CORE_DEBUG_LEVEL=5
    ; Maximum log level for src files and libs, can be higher (or lower, equal) than CORE_DEBUG_LEVEL
	-D LOG_LOCAL_LEVEL=ESP_LOG_DEBUG

; Extend the default build flagswith additional flags for the src directory only
build_src_flags =
	-Og
	-Wall -Wextra
	-Wno-unused-parameter

upload_protocol = esptool
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, log2file

lib_compat_mode = strict
lib_ldf_mode = chain
lib_deps = 
	https://github.com/boskieft/neopixel.git

custom_component_remove = 
	espressif/esp_hosted
	espressif/esp_wifi_remote
	espressif/esp-dsp
	espressif/esp32-camera
	espressif/libsodium
	espressif/esp-modbus
	espressif/qrcode
	espressif/esp_insights
	espressif/esp_diag_data_store
	espressif/esp_diagnostics
	espressif/esp_rainmaker
	espressif/rmaker_common

[env:esp32]
board=wemos_d1_mini32

[env:esp32s2]
board=lolin_s2_mini

[env:esp32s3]
board=lilygo-t3-s3

[env:esp32c3]
board=adafruit_qtpy_esp32c3

[env:esp32c6]
board=seeed_xiao_esp32c6
